### ISSUE TITLE
Clarification.

### ISSUE THREAD

**Issue by loops** [lizmat/unprint#1]
Hi!  Faster is better.  Thanks :-)

It would be interesting to know what the original say/print/put do instead of this and why.  When would the originals be a better choice?  If these ones are faster, what advantage do you get by using the slower originals?

Also,  when using the "unprint" module, will it also get used in the object call case,  such as:
  42.say
  "hello".put

**Comment by lizmat** [comment]
> On 8 Jul 2018, at 16:37, Sean <notifications@github.com> wrote:
> Hi! Faster is better. Thanks :-)

Yeah…  it usually is.


> It would be interesting to know what the original say/print/put do instead of this and why. When would the originals be a better choice? If these ones are faster, what advantage do you get by using the slower originals?

The originals use the complete class hierarchy and properly check $*STOUT and what the proper line ending is for the handle living in $*OUT.

Which you may not need in many cases, especially small scripts.


> Also, when using the "unprint" module, will it also get used in the object call case, such as:
> 42.say
> "hello”.put

No, I don’t intend to do that.  The reason for that is that it’s easy to lexically override subroutines, it is a lot harder to lexically overwrite methods on core classes.


Kind regards,

Liz
